/* =========================================================
   TANDOOR ET GRILLE — full menu (from the real PDF menu)
   Bilingual FR/EN. Prices in CAD, before tax.
   Main dishes use SHARED protein pricing: pick a protein,
   the sauce style is the dish. `proteins` = variant list.
   ========================================================= */
window.TG_MENU = {
  // Standard protein set for the shared-price "Main Dishes"
  PROTEINS: [
    { id: 'chicken', en: 'Chicken', fr: 'Poulet', price: 15.99 },
    { id: 'beef', en: 'Beef', fr: 'Bœuf', price: 15.99 },
    { id: 'lamb', en: 'Lamb', fr: 'Agneau', price: 17.99 },
    { id: 'prawn', en: 'King Prawn', fr: 'Crevettes géantes', price: 20.99 },
  ],
  sections: [
    { id: 'soups', en: 'Soups', fr: 'Soupes', items: [
      { id: 'dal-soup', en: 'Dal Soup', fr: 'Soupe aux lentilles', descEn: 'Comforting lentil soup.', descFr: 'Soupe de lentilles réconfortante.', price: 4.99, veg: true },
      { id: 'chicken-corn-soup', en: 'Chicken Corn Soup', fr: 'Soupe poulet et maïs', price: 4.99 },
    ]},
    { id: 'appetizers', en: 'Appetizers', fr: "Hors d'œuvres", items: [
      { id: 'veg-samosa', en: 'Vegetable Samosa (2 pcs)', fr: 'Samosa aux légumes (2 mcx)', descEn: 'Fried dumplings with potatoes, peas & herbs.', descFr: 'Boulettes frites aux pommes de terre, pois et herbes.', price: 4.49, veg: true },
      { id: 'chana-samosa-chaat', en: 'Chana Samosa Chaat', fr: 'Samosa Chaat', descEn: 'Samosa with chickpeas, yogurt, veg & spices.', descFr: 'Samosa, pois chiches, yogourt, légumes et épices.', price: 8.99, veg: true },
      { id: 'aloo-tikki', en: 'Aloo Tikki + Chana (2 pcs)', fr: 'Aloo Tikki + Chana (2 mcx)', descEn: 'Potato cakes, chickpeas, herbs & chutney.', descFr: 'Galettes de pommes de terre, chana, herbes et chutney.', price: 7.99, veg: true },
      { id: 'spring-rolls', en: 'Spring Rolls (Vegetarian)', fr: 'Rouleaux de printemps (Végé)', descEn: 'Veg, mushrooms, carrots, vermicelli, soya.', descFr: 'Légumes, champignons, carottes, vermicelle, soya.', price: 6.99, veg: true },
      { id: 'onion-bhaji', en: 'Onion Bhaji', fr: 'Oignon Bhaji', descEn: 'Gram-flour onion fritters with herbs & spice.', descFr: 'Beignets d’oignons à la farine de gramme, herbes et épices.', price: 7.99, veg: true },
      { id: 'veg-pakora', en: 'Vegetable Pakoras', fr: 'Pakora aux légumes', descEn: 'Assorted veg fritters in gram-flour batter.', descFr: 'Beignets de légumes assortis à la farine de gramme.', price: 7.99, veg: true },
      { id: 'paneer-pakora', en: 'Paneer Pakora', fr: 'Paneer Pakora', descEn: 'Cottage-cheese fritters, herbs & spice.', descFr: 'Beignets de fromage cottage, herbes et épices.', price: 10.99, veg: true },
      { id: 'fish-pakora', en: 'Fish Pakora', fr: 'Pakora de poisson', descEn: 'Fish in gram-flour batter, herbs & coriander.', descFr: 'Poisson à la farine de gramme, herbes et coriandre.', price: 12.99 },
      { id: 'chicken-pakora', en: 'Chicken Pakora', fr: 'Pakora de poulet', descEn: 'Chicken breast in gram flour, fried with herbs.', descFr: 'Poulet enrobé de farine de gramme, frit aux herbes.', price: 11.99 },
      { id: 'lahori-fish-app', en: 'Lahori Fish', fr: 'Lahori poisson', descEn: '2 whole fried basa in chickpea flour & chili.', descFr: '2 bassa entiers frits, farine de pois chiches et chili.', price: 17.99 },
      { id: 'chili-fish', en: 'Chili Fish (Oriental)', fr: 'Chili poisson', descEn: 'Fish in a special Asian-style chili sauce.', descFr: 'Poisson dans une sauce asiatique épicée.', price: 14.99, spice: 2 },
      { id: 'king-prawn-pakora', en: 'King Prawn Pakora', fr: 'Crevettes géantes Pakora', descEn: 'King prawns in gram flour, fried with herbs.', descFr: 'Crevettes géantes à la farine de gramme, herbes.', price: 19.99 },
      { id: 'chana-bhatura', en: 'Chana Bhatura', fr: 'Chana Bhatura', descEn: 'Two fried puris with chickpeas & spicy pickles.', descFr: 'Deux puris frits, pois chiches et cornichons épicés.', price: 12.99, veg: true },
      { id: 'veg-manchurian-app', en: 'Vegetarian Manchurian', fr: 'Manchurian végétarien', descEn: 'Mixed veg, onions, green chili & soya.', descFr: 'Légumes, oignons, chili vert et soya.', price: 13.99, veg: true, spice: 2 },
      { id: 'crispy-mushrooms', en: 'Crispy Mushrooms', fr: 'Champignons croustillants', descEn: 'Mushrooms in gram flour, fried with herbs.', descFr: 'Champignons à la farine de gramme, frits aux herbes.', price: 14.99, veg: true },
      { id: 'chili-paneer', en: 'Chilli Paneer (Oriental)', fr: 'Chilli Paneer', descEn: 'Cottage cheese in a special Asian chili sauce.', descFr: 'Fromage dans une sauce asiatique épicée.', price: 14.99, veg: true, spice: 2 },
      { id: 'gobi-manchurian', en: 'Gobi Manchurian (Oriental)', fr: 'Gobi Manchurian', descEn: 'Cauliflower, onions, green chili & soya.', descFr: 'Chou-fleur, oignons, chili vert et soya.', price: 13.99, veg: true, spice: 2 },
      { id: 'chicken-manchurian-app', en: 'Chicken Manchurian', fr: 'Poulet Manchurian', descEn: 'Chicken, bell pepper, ginger-garlic & soya.', descFr: 'Poulet, poivrons, gingembre-ail et soya.', price: 15.99, spice: 2 },
      { id: 'papadum', en: 'Papadum + Chutney', fr: 'Papadum + Chutney', descEn: 'Crispy rice-flour bread, mint & tamarind sauce.', descFr: 'Pain croustillant de farine de riz, menthe et tamarin.', price: 1.99, veg: true },
      { id: 'raita', en: 'Raita', fr: 'Raita', descEn: 'Yogurt with vegetables & spices.', descFr: 'Yogourt aux légumes et épices.', price: 3.99, veg: true },
      { id: 'french-fries', en: 'French Fries', fr: 'Frites', price: 7.99, veg: true },
    ]},
    { id: 'salads', en: 'Salads', fr: 'Salades', items: [
      { id: 'chef-salad', en: "Chef's Special Salad", fr: 'Salade spéciale du Chef', descEn: 'Lettuce, tomato, cucumber, onion, carrot, house dressing.', descFr: 'Laitue, tomates, concombre, oignon, carotte, sauce maison.', price: 6.99, veg: true },
      { id: 'onion-salad', en: 'Onion Salad', fr: 'Salade aux oignons', descEn: 'Onions, tomato, cucumber, house dressing.', descFr: 'Oignons, tomates, concombre, sauce maison.', price: 3.99, veg: true },
      { id: 'cucumber-salad', en: 'Cucumber Salad', fr: 'Salade de concombres', descEn: 'Fresh cucumbers, spices & house dressing.', descFr: 'Concombres frais, épices et sauce maison.', price: 4.99, veg: true },
    ]},
    { id: 'rolls', en: 'Rolls', fr: 'Rouleaux', items: [
      { id: 'trio', en: 'Trio', fr: 'Trio', descEn: 'Roll with fries & a drink.', descFr: 'Rouleau avec frites et breuvage.', price: 12.99 },
      { id: 'kebab-roll', en: 'Kebab Roll (beef or chicken)', fr: 'Rouleau Kebab (bœuf ou poulet)', descEn: 'Seekh kebab, salad, tomato, red onion, house sauce in naan.', descFr: 'Seekh kebab, salade, tomates, oignon rouge, sauce maison dans un naan.', price: 7.99 },
      { id: 'chicken-tikka-roll', en: 'Chicken Tikka Roll', fr: 'Rouleau Tikka au poulet', descEn: 'Chicken tikka, salad, tomato, cucumber, onion, house sauce in naan.', descFr: 'Poulet tikka, salade, tomates, concombre, oignon, sauce maison dans un naan.', price: 7.99 },
      { id: 'butter-chicken-roll', en: 'Butter Chicken Roll', fr: 'Rouleau de poulet au beurre', descEn: 'Butter chicken, salad & house sauce in naan.', descFr: 'Poulet au beurre, salade et sauce maison dans un naan.', price: 7.99 },
      { id: 'paneer-tikka-roll', en: 'Paneer Tikka Roll', fr: 'Rouleau Paneer Tikka', descEn: 'Tandoori paneer tikka, salad & house sauce in naan.', descFr: 'Paneer tikka tandoori, salade et sauce maison dans un naan.', price: 7.99, veg: true },
      { id: 'veg-roll', en: 'Vegetarian Roll', fr: 'Rouleau végétarien', descEn: 'Mixed veg, onions, green chili & soya in naan.', descFr: 'Légumes, oignons, chili vert et soya dans un naan.', price: 6.99, veg: true },
    ]},
    { id: 'kebab', en: 'Kebab', fr: 'Kebab', items: [
      { id: 'seekh-kebab', en: 'Seekh Kebab (Beef)', fr: 'Seekh Kebab (Bœuf)', descEn: 'Seasoned ground beef cooked in the tandoor.', descFr: 'Bœuf haché assaisonné, cuit au tandoor.', price: 13.99 },
      { id: 'resham-kebab', en: 'Resham Kebab (Chicken)', fr: 'Resham Kebab (Poulet)', descEn: 'Minced seasoned chicken from the tandoor.', descFr: 'Poulet haché assaisonné, cuit au tandoor.', price: 13.99 },
      { id: 'bihari-kebab', en: 'Bihari Kebab', fr: 'Bihari Kebab', descEn: 'Strips of tenderloin roasted in the tandoor.', descFr: 'Lanières de filet de bœuf grillées au tandoor.', price: 19.99 },
      { id: 'chef-kebab', en: "Chef's Special Kebab", fr: 'Kebab spécial du Chef', descEn: 'Tandoori kebabs with cream, cheese, peppers, mushrooms, paneer & chef sauce.', descFr: 'Brochettes tandoor, crème, fromage, poivrons, champignons, paneer et sauce du chef.', price: 20.99 },
    ]},
    { id: 'bbq-veg', en: 'BBQ Vegetarian Sizzlers', fr: 'Sizzlers végé BBQ', note: 'Cooked on charcoal', noteFr: 'Cuit sur charbon', items: [
      { id: 'paneer-tikka', en: 'Paneer Tikka', fr: 'Paneer Tikka', descEn: 'Grilled homemade cheese, peppers & onions.', descFr: 'Fromage maison grillé, poivrons et oignons.', price: 17.99, veg: true },
      { id: 'achari-paneer-tikka', en: 'Achari Paneer Tikka', fr: 'Achari Paneer Tikka', descEn: 'Paneer in an achari marinade, soft & juicy.', descFr: 'Paneer mariné à l’achari, moelleux et juteux.', price: 18.99, veg: true },
      { id: 'malai-paneer-tikka', en: 'Malai Paneer Tikka', fr: 'Malai Paneer Tikka', descEn: 'Grilled paneer, peppers & onions with cream.', descFr: 'Paneer grillé, poivrons et oignons à la crème.', price: 19.99, veg: true },
      { id: 'tandoori-soya-chaap', en: 'Tandoori Soya Chaap', fr: 'Chaap de soja Tandoori', descEn: 'Soya chaap in yogurt & spice, tandoor-cooked.', descFr: 'Chaap de soja au yogourt et épices, cuit au tandoor.', price: 17.99, veg: true },
      { id: 'malai-soya-chaap', en: 'Malai Soya Chaap', fr: 'Malai Chaap de soja', descEn: 'Soya chaap in seasoned yogurt, tandoor-baked.', descFr: 'Chaap de soja au yogourt assaisonné, cuit au tandoor.', price: 18.99, veg: true },
      { id: 'achari-soya-chaap', en: 'Achari Soya Chaap', fr: 'Achari Soya Chaap', descEn: 'Soya chaap in an achari marinade.', descFr: 'Chaap de soja mariné à l’achari.', price: 17.99, veg: true },
    ]},
    { id: 'mains', en: 'Main Dishes', fr: 'Plats principaux', shared: true,
      note: 'All boneless. Choose your protein — add a spice level (mild / medium / spicy) in the order notes.',
      noteFr: 'Tous désossés. Choisissez votre viande — précisez le niveau d’épices (doux / moyen / épicé) dans les notes.',
      items: [
        { id: 'm-butter', en: 'Butter', fr: 'Au beurre', descEn: 'Rich creamy tomato & butter sauce.', descFr: 'Sauce crémeuse aux tomates et beurre.' },
        { id: 'm-curry', en: 'Curry', fr: 'Curry', descEn: 'Classic tomato & onion sauce.', descFr: 'Sauce de tomates et oignons.' },
        { id: 'm-korma', en: 'Korma', fr: 'Korma', descEn: 'Mild creamy yogurt & herb sauce.', descFr: 'Sauce douce et crémeuse au yogourt et herbes.' },
        { id: 'm-tikka-masala', en: 'Tikka Masala', fr: 'Tikka Masala', descEn: 'Tikka in house masala sauce.', descFr: 'Tikka dans notre sauce masala maison.' },
        { id: 'm-karahi', en: 'Karahi', fr: 'Karahi', descEn: 'Dry, ginger-garlic & fresh coriander.', descFr: 'Sauté sec, gingembre-ail et coriandre fraîche.' },
        { id: 'm-jalfrezi', en: 'Jalfrezi', fr: 'Jalfrezi', descEn: 'Rich sauce with tomato, onion & bell pepper.', descFr: 'Sauce riche aux tomates, oignons et poivrons.' },
        { id: 'm-vindaloo', en: 'Vindaloo', fr: 'Vindaloo', descEn: 'Fiery Goan vinegar & red chili.', descFr: 'Plat de Goa au vinaigre et chili rouge.', spice: 3 },
        { id: 'm-madras', en: 'Madras', fr: 'Madras', descEn: 'Spicy Chennai-style tomato.', descFr: 'Plat épicé de Chennai aux tomates.', spice: 3 },
        { id: 'm-chilli-masala', en: 'Chilli Masala', fr: 'Chilli Masala', descEn: 'Green chili, onions, peppers & coriander.', descFr: 'Chili vert, oignons, poivrons et coriandre.', spice: 2 },
        { id: 'm-saagwalla', en: 'Saagwalla', fr: 'Saagwalla', descEn: 'Fresh spinach, herbs & spice.', descFr: 'Épinards frais, herbes et épices.' },
        { id: 'm-rogan-josh', en: 'Rogan Josh', fr: 'Rogan Josh', descEn: 'Kashmiri chili & dried flowers.', descFr: 'Plat du Kashmir, chili et fleurs séchées.', spice: 3 },
        { id: 'm-bhuna', en: 'Bhuna', fr: 'Bhuna', descEn: 'Slow-cooked with mushroom, pepper & onion.', descFr: 'Mijoté avec champignons, poivrons et oignons.' },
        { id: 'm-achar-gosht', en: 'Achar Gosht', fr: 'Achar Gosht', descEn: 'With spicy pickled vegetables.', descFr: 'Avec légumes marinés épicés.' },
      ]
    },
    { id: 'traditional', en: 'Traditional Specialities', fr: 'Spécialités traditionnelles', items: [
      { id: 'haleem', en: 'Haleem', fr: 'Haleem', descEn: 'Beef stew with mixed lentils & spice.', descFr: 'Ragoût de bœuf, lentilles et épices.', price: 13.99 },
      { id: 'nihari', en: 'Nihari', fr: 'Nihari', descEn: 'Beef with ginger, garam masala, yogurt & butter.', descFr: 'Bœuf, gingembre, garam masala, yogourt et beurre.', price: 14.99 },
      { id: 'lamb-paya', en: 'Lamb Paya', fr: "Paya d'agneau", descEn: 'Lamb trotters with garlic, turmeric, chili & butter.', descFr: 'Pattes d’agneau, ail, curcuma, chili et beurre.', price: 14.99 },
      { id: 'whole-chicken-karahi', en: 'Whole Chicken Karahi (Fresh)', fr: 'Poulet entier Karahi (Frais)', descEn: 'Fresh chicken, tomato, onion, garlic & ginger. Ask for availability.', descFr: 'Poulet frais, tomates, oignons, ail et gingembre. Selon disponibilité.', price: 45.99, big: true },
      { id: 'goat-karahi', en: 'Goat Karahi (1kg)', fr: 'Chèvre Karahi (1kg)', descEn: 'Bone-in goat, tomato, onion, garlic & ginger. Ask for availability.', descFr: 'Chèvre avec os, tomates, oignons, ail et gingembre. Selon disponibilité.', price: 59.99, big: true },
    ]},
    { id: 'balti', en: 'Exotic Balties & Sea Food', fr: 'Balties exotiques & fruits de mer', items: [
      { id: 'balti-chicken', en: 'Balti Chicken', fr: 'Balti au poulet', descEn: 'Balti sauce: tomato, onion & peppers.', descFr: 'Sauce balti : tomates, oignons et poivrons.', price: 16.99 },
      { id: 'balti-beef', en: 'Beef Balti', fr: 'Balti au bœuf', price: 16.99 },
      { id: 'balti-lamb', en: 'Lamb Balti', fr: "Balti à l'agneau", price: 17.99 },
      { id: 'balti-prawn', en: 'King Prawn Balti', fr: 'Balti aux crevettes géantes', price: 20.99 },
      { id: 'fish-curry-basa', en: 'Fish Curry (Basa)', fr: 'Curry de poisson (Bassa)', descEn: 'Basa in a special blend of spices & herbs.', descFr: 'Bassa dans un mélange spécial d’épices et herbes.', price: 15.99 },
      { id: 'fish-curry-salmon', en: 'Fish Curry (Salmon)', fr: 'Curry de poisson (Saumon)', descEn: 'Tandoor-grilled fish in tomato, onion & lemon.', descFr: 'Poisson grillé au tandoor, tomates, oignons et citron.', price: 22.99 },
      { id: 'lahori-fish-main', en: 'Lahori Fish', fr: 'Lahori poisson', descEn: 'Whole fried basa in chickpea flour & chili.', descFr: 'Bassa entier frit, farine de pois chiches et chili.', price: 17.99 },
      { id: 'balti-kebab-masala', en: 'Balti Kebab Masala (chicken/beef)', fr: 'Balti Kebab Masala (poulet/bœuf)', descEn: 'Seekh kebab from the tandoor in our special sauce.', descFr: 'Seekh kebab du tandoor dans notre sauce spéciale.', price: 15.99 },
    ]},
    { id: 'veg', en: 'Vegetarian Specialities', fr: 'Spécialités végétariennes', items: [
      { id: 'karahi-paneer', en: 'Karahi Paneer', fr: 'Karahi Paneer', descEn: 'Dry ginger-garlic-coriander sauce with cottage cheese.', descFr: 'Sauce sèche gingembre-ail-coriandre, fromage blanc.', price: 14.99, veg: true },
      { id: 'shahi-paneer', en: 'Shahi Paneer', fr: 'Shahi Paneer', descEn: 'Cottage cheese in a light creamy sauce.', descFr: 'Fromage blanc, sauce crémeuse légère.', price: 14.99, veg: true },
      { id: 'palak-paneer', en: 'Palak Paneer', fr: 'Palak Paneer', descEn: 'Spinach & cheese with butter, ginger & garlic.', descFr: 'Épinards et fromage, beurre, gingembre et ail.', price: 13.99, veg: true },
      { id: 'paneer-tikka-masala', en: 'Paneer Tikka Masala', fr: 'Paneer Tikka Masala', descEn: 'Grilled paneer cubes with tomato, pepper & onion.', descFr: 'Cubes de paneer grillés, tomates, poivrons et oignons.', price: 14.99, veg: true },
      { id: 'matar-paneer', en: 'Matar Paneer', fr: 'Matar Paneer', descEn: 'Peas & cheese in a mildly spicy sauce.', descFr: 'Pois et fromage, sauce légèrement épicée.', price: 13.99, veg: true, spice: 1 },
      { id: 'paneer-korma', en: 'Paneer Korma', fr: 'Paneer Korma', descEn: 'Cheese cubes with yogurt & ground coriander.', descFr: 'Cubes de fromage, yogourt et coriandre moulue.', price: 13.99, veg: true },
      { id: 'malai-kofta', en: 'Malai Kofta', fr: 'Malai Kofta', descEn: 'Cheese & potato dumplings in creamy sauce.', descFr: 'Boulettes fromage-pomme de terre, sauce crémeuse.', price: 13.99, veg: true },
      { id: 'mixed-veg', en: 'Mixed Vegetables', fr: 'Mélange de légumes', descEn: 'Mixed veg with oriental spices.', descFr: 'Légumes mélangés aux épices orientales.', price: 11.99, veg: true },
      { id: 'veg-jalfrezi', en: 'Veg Jalfrezi', fr: 'Veg Jalfrezi', descEn: 'Mixed veg, tomato, ginger, onion & pepper.', descFr: 'Légumes, tomates, gingembre, oignons et poivrons.', price: 13.99, veg: true },
      { id: 'sarson-saag', en: 'Sarson ka Saag', fr: 'Sarson ka Saag', descEn: 'Mustard leaves with butter, ginger & garlic.', descFr: 'Feuilles de moutarde, beurre, gingembre et ail.', price: 11.99, veg: true },
      { id: 'nauratan-korma', en: 'Nauratan Korma', fr: 'Nauratan Korma', descEn: 'Garden veg in a rich yogurt sauce.', descFr: 'Légumes du jardin, sauce riche au yogourt.', price: 13.99, veg: true },
      { id: 'dal-makhani', en: 'Dal Makhani', fr: 'Dal Makhani', descEn: 'Black & yellow lentils finished with butter.', descFr: 'Lentilles noires et jaunes, finies au beurre.', price: 12.99, veg: true },
      { id: 'dal-mash', en: 'Dal Mash', fr: 'Dal Mash', descEn: 'Split yellow lentils, ginger, garlic & spice.', descFr: 'Lentilles jaunes cassées, gingembre, ail et épices.', price: 14.99, veg: true },
      { id: 'dal-chana', en: 'Dal Chana', fr: 'Dal Chana', descEn: 'Yellow lentils, ginger, garlic & spice.', descFr: 'Lentilles jaunes, gingembre, ail et épices.', price: 12.99, veg: true },
      { id: 'yellow-dal', en: 'Yellow Dal / Dal Tadka', fr: 'Yellow Dal / Dal Tadka', descEn: 'Yellow lentils, aromatics, tomato & spiced oil.', descFr: 'Lentilles jaunes, aromates, tomates et huile épicée.', price: 10.99, veg: true },
      { id: 'chana-masala', en: 'Chana Masala', fr: 'Chana Masala', descEn: 'Chickpeas with ginger, garlic & spice.', descFr: 'Pois chiches, gingembre, ail et épices.', price: 10.99, veg: true },
      { id: 'bhindi', en: 'Bhindi (Okra)', fr: 'Bhindi (Gombo)', descEn: 'Okra with herbs & spice.', descFr: 'Gombo aux herbes et épices.', price: 12.99, veg: true },
      { id: 'karela', en: 'Karela', fr: 'Karela', descEn: 'Bitter melon with herbs & spice.', descFr: 'Melon amer aux herbes et épices.', price: 11.99, veg: true },
      { id: 'baigan-bharta', en: 'Baigan Bharta', fr: 'Baigan Bharta', descEn: 'Eggplant with tomato, onion, garlic & ginger.', descFr: 'Aubergine, tomates, oignons, ail et gingembre.', price: 11.99, veg: true },
      { id: 'mushroom-jalfrezi', en: 'Mushroom Jalfrezi', fr: 'Champignons Jalfrezi', descEn: 'Mushrooms sautéed with onion, tomato & pepper.', descFr: 'Champignons sautés, oignons, tomates et poivrons.', price: 13.99, veg: true },
      { id: 'aloo-gobi', en: 'Aloo Gobi', fr: 'Aloo Gobi', descEn: 'Potato & cauliflower with herbs & spice.', descFr: 'Pommes de terre et chou-fleur, herbes et épices.', price: 11.99, veg: true },
      { id: 'aloo-matar', en: 'Aloo Matar', fr: 'Aloo Matar', descEn: 'Potato & peas with herbs & spice.', descFr: 'Pommes de terre et pois, herbes et épices.', price: 11.99, veg: true },
      { id: 'aloo-palak', en: 'Aloo Palak', fr: 'Aloo Palak', descEn: 'Potato & spinach with herbs & spice.', descFr: 'Pommes de terre et épinards, herbes et épices.', price: 11.99, veg: true },
      { id: 'aloo-korma', en: 'Aloo Korma', fr: 'Aloo Korma', descEn: 'Potatoes in a mild creamy sauce.', descFr: 'Pommes de terre, sauce douce et crémeuse.', price: 10.99, veg: true },
      { id: 'soya-chaap-karahi', en: 'Soya Chaap Karahi', fr: 'Soya Chaap Karahi', descEn: 'Dry ginger-garlic-coriander sauce with soya.', descFr: 'Sauce sèche gingembre-ail-coriandre, soja.', price: 14.99, veg: true },
    ]},
    { id: 'biryani', en: 'Biryani & Rice', fr: 'Biryani & Riz', items: [
      { id: 'chicken-biryani', en: 'Chicken Biryani', fr: 'Biryani au poulet', descEn: 'Chicken & basmati with saffron & whole spice.', descFr: 'Poulet et basmati, safran et épices entières.', price: 14.99 },
      { id: 'butter-chicken-biryani', en: 'Butter Chicken Biryani', fr: 'Biryani poulet au beurre', descEn: 'Butter chicken layered with saffron basmati.', descFr: 'Poulet au beurre et basmati au safran.', price: 14.99 },
      { id: 'lamb-biryani', en: 'Lamb Biryani', fr: "Biryani à l'agneau", price: 16.99 },
      { id: 'beef-biryani', en: 'Beef Biryani', fr: 'Biryani au bœuf', price: 14.99 },
      { id: 'fish-biryani', en: 'Fish Biryani', fr: 'Biryani au poisson', descEn: 'Stewed fish with mint & herbs, layered with rice.', descFr: 'Poisson mijoté à la menthe et herbes, sur riz.', price: 15.99 },
      { id: 'prawn-biryani', en: 'King Prawn Biryani', fr: 'Biryani aux crevettes géantes', price: 22.99 },
      { id: 'veg-biryani', en: 'Vegetarian Biryani', fr: 'Biryani végétarien', price: 12.99, veg: true },
      { id: 'chicken-fried-rice', en: 'Chicken Fried Rice', fr: 'Riz frit au poulet', descEn: 'Chicken & peas with herbs & spice.', descFr: 'Poulet et pois, herbes et épices.', price: 12.99 },
      { id: 'matar-pulao', en: 'Matar Pulao (Peas)', fr: 'Matar Pulao (Pois)', descEn: 'Peas in basmati with aromatic spices.', descFr: 'Pois dans du basmati, épices aromatiques.', price: 8.99, veg: true },
      { id: 'basmati-rice', en: 'Basmati Rice', fr: 'Riz basmati', price: 4.99, veg: true },
      { id: 'saffron-rice', en: 'Saffron Rice', fr: 'Riz safran', price: 6.99, veg: true },
      { id: 'garlic-rice', en: 'Garlic Rice', fr: "Riz à l'ail", price: 7.99, veg: true },
      { id: 'jeera-rice', en: 'Jeera / Cumin Rice', fr: 'Riz au cumin', price: 6.99, veg: true },
    ]},
    { id: 'bread', en: 'Bread', fr: 'Pain', note: 'Baked fresh in the tandoor.', items: [
      { id: 'naan', en: 'Naan', fr: 'Naan', price: 2.49, veg: true },
      { id: 'sesame-naan', en: 'Kulcha / Sesame Naan', fr: 'Kulcha / Naan au sésame', price: 3.49, veg: true },
      { id: 'coriander-naan', en: 'Coriander Naan', fr: 'Naan à la coriandre', price: 3.99, veg: true },
      { id: 'garlic-naan', en: 'Garlic Naan', fr: "Naan à l'ail", price: 3.99, veg: true },
      { id: 'onion-naan', en: 'Onion Naan', fr: 'Naan aux oignons', price: 5.99, veg: true },
      { id: 'paneer-naan', en: 'Paneer Naan (Cheese)', fr: 'Paneer Naan (Fromage)', price: 5.99, veg: true },
      { id: 'aloo-naan', en: 'Aloo Naan (Potato)', fr: 'Aloo Naan (Pommes de terre)', price: 5.99, veg: true },
      { id: 'keema-naan', en: 'Keema Naan (chicken or beef)', fr: 'Keema Naan (poulet ou bœuf)', price: 7.99 },
      { id: 'roti', en: 'Roti (Whole Wheat)', fr: 'Roti (Blé entier)', price: 3.99, veg: true },
      { id: 'lacha-paratha', en: 'Tandoori Lacha Paratha', fr: 'Tandoori Lacha Paratha', price: 6.99, veg: true },
      { id: 'amritsari-kulcha', en: 'Amritsari Kulcha', fr: 'Amrit Sari Kulcha', descEn: 'Stuffed with mashed potato, onion & spice.', descFr: 'Farci de purée de pommes de terre, oignon et épices.', price: 5.99, veg: true },
      { id: 'amritsari-kulcha-chana', en: 'Amritsari Kulcha + Chana', fr: 'Amrit Sari Kulcha + Chana', descEn: 'Stuffed kulcha + chana masala + salad.', descFr: 'Kulcha farci + chana masala + salade.', price: 13.99, veg: true },
    ]},
    { id: 'desserts', en: 'Desserts', fr: 'Desserts', items: [
      { id: 'kheer', en: 'Kheer', fr: 'Kheer', descEn: 'Sweet rice pudding with pistachios.', descFr: 'Pudding au riz sucré, pistaches.', price: 4.99, veg: true },
      { id: 'gulab-jamun', en: 'Gulab Jamun', fr: 'Gulab Jamun', descEn: 'Milk balls in sugar & rose water, peanuts.', descFr: 'Boules de lait, sucre et eau de rose, arachides.', price: 4.99, veg: true },
      { id: 'ras-malai', en: 'Ras Malai', fr: 'Ras Malai', descEn: 'Cheese patties in rich cream, nuts.', descFr: 'Galettes de fromage, crème riche, noix.', price: 6.99, veg: true },
      { id: 'gajar-halwa', en: 'Gajar Halwa', fr: 'Gajar Halwa', descEn: 'Carrot, milk & clarified butter.', descFr: 'Carottes, lait et beurre clarifié.', price: 6.99, veg: true },
      { id: 'kulfi', en: 'Kulfi (mango or vanilla)', fr: 'Kulfi (mangue ou vanille)', price: 4.49, veg: true },
      { id: 'falooda-kulfi', en: 'Falooda Matka Kulfi', fr: 'Falooda Matka Kulfi', descEn: 'Basil seeds, falooda noodles, rose syrup & malai kulfi.', descFr: 'Graines de basilic, nouilles falooda, sirop de rose et malai kulfi.', price: 7.99, veg: true },
    ]},
    { id: 'drinks', en: 'Drinks', fr: 'Boissons', items: [
      { id: 'mango-lassi', en: 'Mango Lassi', fr: 'Lassi à la mangue', price: 4.99, veg: true },
      { id: 'lassi', en: 'Lassi (sweet or salty)', fr: 'Lassi (sucré ou salé)', price: 3.99, veg: true },
      { id: 'kashmiri-chai', en: 'Kashmiri Chai (Pink Tea)', fr: 'Kashmiri Chai (Thé rose)', price: 4.99, veg: true },
      { id: 'soft-drink', en: 'Soft Drinks', fr: 'Boissons gazeuses', price: 2.49, veg: true },
      { id: 'perrier', en: 'Perrier Water', fr: 'Eau Perrier', price: 2.49, veg: true },
      { id: 'lemon-soda', en: 'Lemon Soda', fr: 'Soda au citron', price: 2.49, veg: true },
      { id: 'chai', en: 'Chai (Milk Tea)', fr: 'Chai (Thé au lait)', price: 4.99, veg: true },
      { id: 'masala-chai', en: 'Masala Chai', fr: 'Masala Chai', price: 3.99, veg: true },
      { id: 'green-tea', en: 'Green Tea', fr: 'Thé vert', price: 2.99, veg: true },
    ]},
  ],
};
